# Generated by Django 5.2.5 on 2025-09-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_alter_address_options_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='published_books',
        ),
        migrations.AddField(
            model_name='book',
            name='published_in_countries',
            field=models.ManyToManyField(related_name='books', to='book_outlet.country'),
        ),
    ]
