# Generated by Django 5.2.5 on 2025-09-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_remove_country_published_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_in_countries',
            field=models.ManyToManyField(to='book_outlet.country'),
        ),
    ]
